DISEASE_DESCRIPTIONS = {
    "(Vertigo) Paroxysmal Positional Vertigo": "(Vertigo) Paroxysmal Positional Vertigo is a medical condition. Description is under development.",
    "AIDS": "AIDS is a medical condition. Description is under development.",
    "Acne": "Acne is a medical condition. Description is under development.",
    "Alcoholic hepatitis": "Alcoholic hepatitis is a medical condition. Description is under development.",
    "Allergy": "Allergy is a medical condition. Description is under development.",
    "Arthritis": "Arthritis is a medical condition. Description is under development.",
    "Bronchial Asthma": "Bronchial Asthma is a medical condition. Description is under development.",
    "Cervical spondylosis": "Cervical spondylosis is a medical condition. Description is under development.",
    "Chicken pox": "Chicken pox is a medical condition. Description is under development.",
    "Chronic cholestasis": "Chronic cholestasis is a medical condition. Description is under development.",
    "Common Cold": "Common Cold is a medical condition. Description is under development.",
    "Dengue": "Dengue is a medical condition. Description is under development.",
    "Diabetes": "Diabetes is a medical condition. Description is under development.",
    "Dimorphic hemorrhoids (piles)": "Dimorphic hemorrhoids (piles) is a medical condition. Description is under development.",
    "Drug Reaction": "Drug Reaction is a medical condition. Description is under development.",
    "Fungal infection": "Fungal infection is a medical condition. Description is under development.",
    "GERD": "GERD is a medical condition. Description is under development.",
    "Gastroenteritis": "Gastroenteritis is a medical condition. Description is under development.",
    "Heart attack": "Heart attack is a medical condition. Description is under development.",
    "Hepatitis A": "Hepatitis A is a medical condition. Description is under development.",
    "Hepatitis B": "Hepatitis B is a medical condition. Description is under development.",
    "Hepatitis C": "Hepatitis C is a medical condition. Description is under development.",
    "Hepatitis D": "Hepatitis D is a medical condition. Description is under development.",
    "Hepatitis E": "Hepatitis E is a medical condition. Description is under development.",
    "Hypertension": "Hypertension is a medical condition. Description is under development.",
    "Hyperthyroidism": "Hyperthyroidism is a medical condition. Description is under development.",
    "Hypoglycemia": "Hypoglycemia is a medical condition. Description is under development.",
    "Hypothyroidism": "Hypothyroidism is a medical condition. Description is under development.",
    "Impetigo": "Impetigo is a medical condition. Description is under development.",
    "Jaundice": "Jaundice is a medical condition. Description is under development.",
    "Malaria": "Malaria is a medical condition. Description is under development.",
    "Migraine": "Migraine is a medical condition. Description is under development.",
    "Osteoarthritis": "Osteoarthritis is a medical condition. Description is under development.",
    "Paralysis (brain hemorrhage)": "Paralysis (brain hemorrhage) is a medical condition. Description is under development.",
    "Peptic ulcer disease": "Peptic ulcer disease is a medical condition. Description is under development.",
    "Pneumonia": "Pneumonia is a medical condition. Description is under development.",
    "Psoriasis": "Psoriasis is a medical condition. Description is under development.",
    "Tuberculosis": "Tuberculosis is a medical condition. Description is under development.",
    "Typhoid": "Typhoid is a medical condition. Description is under development.",
    "Urinary tract infection": "Urinary tract infection is a medical condition. Description is under development.",
    "Varicose veins": "Varicose veins is a medical condition. Description is under development.",
}

DISEASE_RECOMMENDATIONS = {
    "(Vertigo) Paroxysmal Positional Vertigo": "Recommendation for (vertigo) paroxysmal positional vertigo will be provided by a healthcare professional.",
    "AIDS": "Recommendation for aids will be provided by a healthcare professional.",
    "Acne": "Recommendation for acne will be provided by a healthcare professional.",
    "Alcoholic hepatitis": "Recommendation for alcoholic hepatitis will be provided by a healthcare professional.",
    "Allergy": "Recommendation for allergy will be provided by a healthcare professional.",
    "Arthritis": "Recommendation for arthritis will be provided by a healthcare professional.",
    "Bronchial Asthma": "Recommendation for bronchial asthma will be provided by a healthcare professional.",
    "Cervical spondylosis": "Recommendation for cervical spondylosis will be provided by a healthcare professional.",
    "Chicken pox": "Recommendation for chicken pox will be provided by a healthcare professional.",
    "Chronic cholestasis": "Recommendation for chronic cholestasis will be provided by a healthcare professional.",
    "Common Cold": "Recommendation for common cold will be provided by a healthcare professional.",
    "Dengue": "Recommendation for dengue will be provided by a healthcare professional.",
    "Diabetes": "Recommendation for diabetes will be provided by a healthcare professional.",
    "Dimorphic hemorrhoids (piles)": "Recommendation for dimorphic hemorrhoids (piles) will be provided by a healthcare professional.",
    "Drug Reaction": "Recommendation for drug reaction will be provided by a healthcare professional.",
    "Fungal infection": "Recommendation for fungal infection will be provided by a healthcare professional.",
    "GERD": "Recommendation for gerd will be provided by a healthcare professional.",
    "Gastroenteritis": "Recommendation for gastroenteritis will be provided by a healthcare professional.",
    "Heart attack": "Recommendation for heart attack will be provided by a healthcare professional.",
    "Hepatitis A": "Recommendation for hepatitis a will be provided by a healthcare professional.",
    "Hepatitis B": "Recommendation for hepatitis b will be provided by a healthcare professional.",
    "Hepatitis C": "Recommendation for hepatitis c will be provided by a healthcare professional.",
    "Hepatitis D": "Recommendation for hepatitis d will be provided by a healthcare professional.",
    "Hepatitis E": "Recommendation for hepatitis e will be provided by a healthcare professional.",
    "Hypertension": "Recommendation for hypertension will be provided by a healthcare professional.",
    "Hyperthyroidism": "Recommendation for hyperthyroidism will be provided by a healthcare professional.",
    "Hypoglycemia": "Recommendation for hypoglycemia will be provided by a healthcare professional.",
    "Hypothyroidism": "Recommendation for hypothyroidism will be provided by a healthcare professional.",
    "Impetigo": "Recommendation for impetigo will be provided by a healthcare professional.",
    "Jaundice": "Recommendation for jaundice will be provided by a healthcare professional.",
    "Malaria": "Recommendation for malaria will be provided by a healthcare professional.",
    "Migraine": "Recommendation for migraine will be provided by a healthcare professional.",
    "Osteoarthritis": "Recommendation for osteoarthritis will be provided by a healthcare professional.",
    "Paralysis (brain hemorrhage)": "Recommendation for paralysis (brain hemorrhage) will be provided by a healthcare professional.",
    "Peptic ulcer disease": "Recommendation for peptic ulcer disease will be provided by a healthcare professional.",
    "Pneumonia": "Recommendation for pneumonia will be provided by a healthcare professional.",
    "Psoriasis": "Recommendation for psoriasis will be provided by a healthcare professional.",
    "Tuberculosis": "Recommendation for tuberculosis will be provided by a healthcare professional.",
    "Typhoid": "Recommendation for typhoid will be provided by a healthcare professional.",
    "Urinary tract infection": "Recommendation for urinary tract infection will be provided by a healthcare professional.",
    "Varicose veins": "Recommendation for varicose veins will be provided by a healthcare professional.",
}
    