from collections import defaultdict

SYMPTOMS = [
    'itching',
    'skin_rash',
    'nodal_skin_eruptions',
    'continuous_sneezing',
    'shivering',
    'chills',
    'joint_pain',
    'stomach_pain',
    'acidity',
    'ulcers_on_tongue',
    'muscle_wasting',
    'vomiting',
    'burning_micturition',
    'spotting_urination',
    'fatigue',
    'weight_gain',
    'anxiety',
    'cold_hands_and_feets',
    'mood_swings',
    'weight_loss',
    'restlessness',
    'lethargy',
    'patches_in_throat',
    'irregular_sugar_level',
    'cough',
    'high_fever',
    'sunken_eyes',
    'breathlessness',
    'sweating',
    'dehydration',
    'indigestion',
    'headache',
    'yellowish_skin',
    'dark_urine',
    'nausea',
    'loss_of_appetite',
    'pain_behind_the_eyes',
    'back_pain',
    'constipation',
    'abdominal_pain',
    'diarrhoea',
    'mild_fever',
    'yellow_urine',
    'yellowing_of_eyes',
    'acute_liver_failure',
    'fluid_overload',
    'swelling_of_stomach',
    'swelled_lymph_nodes',
    'malaise',
    'blurred_and_distorted_vision',
    'phlegm',
    'throat_irritation',
    'redness_of_eyes',
    'sinus_pressure',
    'runny_nose',
    'congestion',
    'chest_pain',
    'weakness_in_limbs',
    'fast_heart_rate',
    'pain_during_bowel_movements',
    'pain_in_anal_region',
    'bloody_stool',
    'irritation_in_anus',
    'neck_pain',
    'dizziness',
    'cramps',
    'bruising',
    'obesity',
    'swollen_legs',
    'swollen_blood_vessels',
    'puffy_face_and_eyes',
    'enlarged_thyroid',
    'brittle_nails',
    'swollen_extremeties',
    'excessive_hunger',
    'extra_marital_contacts',
    'drying_and_tingling_lips',
    'slurred_speech',
    'knee_pain',
    'hip_joint_pain',
    'muscle_weakness',
    'stiff_neck',
    'swelling_joints',
    'movement_stiffness',
    'spinning_movements',
    'loss_of_balance',
    'unsteadiness',
    'weakness_of_one_body_side',
    'loss_of_smell',
    'bladder_discomfort',
    'foul_smell_of_urine',
    'continuous_feel_of_urine',
    'passage_of_gases',
    'internal_itching',
    'toxic_look_(typhos)',
    'depression',
    'irritability',
    'muscle_pain',
    'altered_sensorium',
    'red_spots_over_body',
    'belly_pain',
    'abnormal_menstruation',
    'dischromic_patches',
    'watering_from_eyes',
    'increased_appetite',
    'polyuria',
    'family_history',
    'mucoid_sputum',
    'rusty_sputum',
    'lack_of_concentration',
    'visual_disturbances',
    'receiving_blood_transfusion',
    'receiving_unsterile_injections',
    'coma',
    'stomach_bleeding',
    'distention_of_abdomen',
    'history_of_alcohol_consumption',
    'fluid_overload.1',
    'blood_in_sputum',
    'prominent_veins_on_calf',
    'palpitations',
    'painful_walking',
    'pus_filled_pimples',
    'blackheads',
    'scurring',
    'skin_peeling',
    'silver_like_dusting',
    'small_dents_in_nails',
    'inflammatory_nails',
    'blister',
    'red_sore_around_nose',
    'yellow_crust_ooze',
    'Unnamed: 133',
]

SYMPTOM_BLOCKS = [
    {'title': 'Skin', 'icon': '🩺', 'symptoms': ['itching', 'skin_rash', 'nodal_skin_eruptions', 'yellowish_skin', 'internal_itching', 'skin_peeling']},
    {'title': 'Other', 'icon': '🩺', 'symptoms': ['continuous_sneezing', 'shivering', 'chills', 'acidity', 'ulcers_on_tongue', 'burning_micturition', 'weight_gain', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'dehydration', 'indigestion', 'headache', 'nausea', 'diarrhoea', 'fluid_overload', 'malaise', 'phlegm', 'throat_irritation', 'runny_nose', 'congestion', 'weakness_in_limbs', 'bloody_stool', 'irritation_in_anus', 'cramps', 'obesity', 'swollen_legs', 'swollen_blood_vessels', 'enlarged_thyroid', 'brittle_nails', 'swollen_extremeties', 'excessive_hunger', 'extra_marital_contacts', 'drying_and_tingling_lips', 'stiff_neck', 'movement_stiffness', 'spinning_movements', 'unsteadiness', 'weakness_of_one_body_side', 'bladder_discomfort', 'toxic_look_(typhos)', 'irritability', 'altered_sensorium', 'red_spots_over_body', 'dischromic _patches', 'polyuria', 'family_history', 'mucoid_sputum', 'rusty_sputum', 'lack_of_concentration', 'visual_disturbances', 'receiving_blood_transfusion', 'receiving_unsterile_injections', 'coma', 'distention_of_abdomen', 'history_of_alcohol_consumption', 'fluid_overload.1', 'blood_in_sputum', 'prominent_veins_on_calf', 'palpitations', 'pus_filled_pimples', 'blackheads', 'scurring', 'silver_like_dusting', 'small_dents_in_nails', 'inflammatory_nails', 'blister', 'red_sore_around_nose', 'yellow_crust_ooze', 'Unnamed: 133']},
    {'title': 'General', 'icon': '🩺', 'symptoms': ['joint_pain', 'stomach_pain', 'fatigue', 'high_fever', 'back_pain', 'abdominal_pain', 'mild_fever', 'pain_during_bowel_movements', 'pain_in_anal_region', 'neck_pain', 'knee_pain', 'hip_joint_pain', 'muscle_pain', 'belly_pain', 'painful_walking']},
    {'title': 'Muscular', 'icon': '🩺', 'symptoms': ['muscle_wasting', 'swelling_of_stomach', 'muscle_weakness', 'swelling_joints']},
    {'title': 'Gastrointestinal', 'icon': '🩺', 'symptoms': ['vomiting', 'loss_of_appetite', 'constipation', 'increased_appetite']},
    {'title': 'Urinary', 'icon': '🩺', 'symptoms': ['spotting_urination', 'dark_urine', 'yellow_urine', 'foul_smell_of_urine', 'continuous_feel_of_urine']},
    {'title': 'Psychological', 'icon': '🩺', 'symptoms': ['anxiety', 'mood_swings', 'depression']},
    {'title': 'Temperature Regulation', 'icon': '🩺', 'symptoms': ['cold_hands_and_feets', 'sweating']},
    {'title': 'Respiratory', 'icon': '🩺', 'symptoms': ['cough', 'breathlessness']},
    {'title': 'Visual', 'icon': '🩺', 'symptoms': ['sunken_eyes', 'pain_behind_the_eyes', 'yellowing_of_eyes', 'blurred_and_distorted_vision', 'redness_of_eyes', 'puffy_face_and_eyes', 'watering_from_eyes']},
    {'title': 'Digestive', 'icon': '🩺', 'symptoms': ['acute_liver_failure', 'passage_of_gases']},
    {'title': 'Immune', 'icon': '🩺', 'symptoms': ['swelled_lymph_nodes']},
    {'title': 'Cardiovascular', 'icon': '🩺', 'symptoms': ['sinus_pressure', 'chest_pain']},
    {'title': 'Hearing', 'icon': '🩺', 'symptoms': ['fast_heart_rate']},
    {'title': 'Neurological', 'icon': '🩺', 'symptoms': ['dizziness', 'slurred_speech', 'loss_of_balance']},
    {'title': 'Circulatory', 'icon': '🩺', 'symptoms': ['bruising', 'stomach_bleeding']},
    {'title': 'Nervous', 'icon': '🩺', 'symptoms': ['loss_of_smell']},
    {'title': 'Hormonal', 'icon': '🩺', 'symptoms': ['abnormal_menstruation']},
]